<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-24CUK9I" failures="15" tests="38" name="Surefire test" time="62.957" errors="0" timestamp="11 Jun 2024 08:36:52 GMT">
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="3.157"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.497">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at api.TestCases.TestBulkDeleteData.testDeleteUser(TestBulkDeleteData.java:16)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.527">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at api.TestCases.TestBulkDeleteData.testDeleteUser(TestBulkDeleteData.java:16)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.526"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.281"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.677"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.482"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.439"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.551"/>
  <testcase classname="api.TestCases.TestBulkDeleteData" name="testDeleteUser" time="1.609">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at api.TestCases.TestBulkDeleteData.testDeleteUser(TestBulkDeleteData.java:16)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.442">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.478">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.601">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.641">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.546">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.707">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.535">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.203">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.473">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkGetData" name="testBulkGetData" time="1.649">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at api.TestCases.TestBulkGetData.testBulkGetData(TestBulkGetData.java:18)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testBulkGetData -->
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.624"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.401"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.535"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.321"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.224"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.49"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.526"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.37"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.363"/>
  <testcase classname="api.TestCases.TestBulkPostData" name="validateBulkPost" time="1.454"/>
  <testcase classname="api.TestCases.SampleTests" name="postData" time="1.433"/>
  <testcase classname="api.TestCases.TestUserAPI" name="testPostUser" time="1.375"/>
  <testcase classname="api.TestCases.SampleTests" name="updateData" time="2.975"/>
  <testcase classname="api.TestCases.TestUserAPI" name="testGetUser" time="1.767"/>
  <testcase classname="api.TestCases.SampleTests" name="getData" time="1.186"/>
  <testcase classname="api.TestCases.TestUserAPI" name="testUpdateUser" time="1.509">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
	at api.TestCases.TestUserAPI.testUpdateUser(TestUserAPI.java:75)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.TestCases.SampleTests" name="deleteData" time="2.9"/>
  <testcase classname="api.TestCases.TestUserAPI" name="testDeleteUser" time="1.699">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at api.TestCases.TestUserAPI.testDeleteUser(TestUserAPI.java:84)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- Surefire test -->
